"""The codec must reproduce frozen container bytes exactly.

tests/data/codec_reference.json is generated by tests/_gen_codec_reference.py
against the codec as it stood before the numpy bit-array vectorisation. Any
change that alters an emitted byte, the accounting total, or the reconstructed
object fails here. Regenerate the reference only for an intended container
format change, and say so in the commit message.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import pytest

from deductive.codecs import decode

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
REF_PATH = HERE / "data" / "codec_reference.json"

if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import _gen_codec_reference as _gen  # noqa: E402

if not REF_PATH.is_file():  # pragma: no cover
    pytest.skip("codec_reference.json not generated", allow_module_level=True)

REF = json.loads(REF_PATH.read_text(encoding="utf-8"))
CASES = [(name, make) for name, make in _gen.cases()]
IDS = [n for n, _ in CASES]


@pytest.mark.parametrize("name,make", CASES, ids=IDS)
def test_container_bytes_match_reference(name, make):
    assert name in REF, f"no frozen reference for {name!r}; regenerate deliberately"
    exp = REF[name]
    enc = make()
    got = enc.data

    assert len(got) == exp["len"], f"{name}: length {len(got)} != frozen {exp['len']}"
    assert hashlib.sha256(got).hexdigest() == exp["sha256"], f"{name}: container bytes changed"
    if "hex" in exp:
        assert got.hex() == exp["hex"], f"{name}: container bytes changed"
    assert enc.accounting.total_bits == exp["accounting_total_bits"], f"{name}: accounting changed"


@pytest.mark.parametrize("name,make", CASES, ids=IDS)
def test_reconstruction_matches_reference(name, make):
    exp = REF[name]
    recon = decode(make().data)
    assert len(recon) == exp["reconstruction_len"], f"{name}: reconstruction length changed"
    assert (
        hashlib.sha256(recon).hexdigest() == exp["reconstruction_sha256"]
    ), f"{name}: codec decodes to a different object than the reference codec"


@pytest.mark.parametrize("name,make", CASES, ids=IDS)
def test_encoder_deterministic(name, make):
    assert make().data == make().data, f"{name}: encoder output is not deterministic"
